### ISSUE TITLE
Decide on title

### ISSUE THREAD

**Issue by JJ** [JJ/edubots-paper#4]
We need to provide a meaningful title for the paper.

**Comment by JJ** [comment]
Some suggestions:
"Evaluating attitudes of higher education teachers towards the use of messaging applications and chatbots"
o
"Teacher preferences and attituted about messaging and chatbots in higher education."

**Comment by aguillenATC** [comment]
more suggestions:
"Chatbots in the classroom: a [preliminary] analysis from the professor's perspective"

**Comment by pacastillo** [comment]
Me gusta más (creo más sintética y comprensible) la segunda:  "Teacher preferences and attitudes about messaging and chatbots in higher education."

**Comment by JJ** [comment]
> more suggestions:
> "Chatbots in the classroom: a [preliminary] analysis from the professor's perspective"

Probably "teacher" is better than professor, a more generic term.
