### ISSUE TITLE
Analyze state of the art in student/teacher preferences towards messaging and chatbots

### ISSUE THREAD

**Issue by JJ** [JJ/edubots-paper#6]

**Comment by NoorhanAbbas** [comment]
The use of WhatsApp in HE both by educators and students  refs #6

**Comment by JJ** [comment]
@NoorhanAbbas do you have any reference? We add them to the [.bib file in the repo](https://github.com/JJ/edubots-paper/blob/main/edubots.bib)

**Comment by JJ** [comment]
The general idea is to first add it to the bib file, and then eventually it integrate into the state of the art section of the paper. Thanks a lot!

**Comment by NoorhanAbbas** [comment]
Right, I get it now.  Sorry about that!  I will be adding nice references now.

Thanks,
Noorhan
________________________________

**Comment by JJ** [comment]
El lun, 17 may 2021 a las 17:29, NoorhanAbbas ***@***.***>)
escribió:

> Right, I get it now. Sorry about that! I will be adding nice references
> now.
>

No problem absolutely. Happy to help :-)

**Comment by NoorhanAbbas** [comment]
Thanks a lot,
Noorhan
________________________________

**Comment by NoorhanAbbas** [comment]
Hello JJ,
I couldn't figure out how to add a reference to the following paper!
https://publications.waset.org/10011648/a-survey-of-whatsapp-as-a-tool-for-instructor-learner-dialogue-learner-content-dialogue-and-learner-learner-dialogue
A Survey of WhatsApp as a Tool for Instructor-Learner Dialogue, Learner-Content Dialogue, and Learner-Learner Dialogue<https://publications.waset.org/10011648/a-survey-of-whatsapp-as-a-tool-for-instructor-learner-dialogue-learner-content-dialogue-and-learner-learner-dialogue>
Dialogue, and Learner-Learner Dialogue
publications.waset.org


Could you point me to the steps to upload it please.

Thanks ever so much,
Noorhan
________________________________

**Comment by JJ** [comment]
@NoorhanAbbas 
1. Go to the page you mention. There's generally a link to the bibtex reference; it's at the bottom, in blue, between Chicago and APA. Copy to clipboard
2. Go to the [`.bib` file](https://github.com/JJ/edubots-paper/blob/main/edubots.bib). Click on the little pencil, at the top, will drop you into an editor. Paste it at the top or bottom, wherever you want.
3. It will tell you have no permission to edit, but you can still suggest a change creating a "pull request". Do so, and write whatever you want in the commit message (slot at the bottom, equivalent to "saving" it), remembering to include a #6 in that message so that it refers back to this issue (as the additions by @fbarranco above show)

Should you get stuck somewhere, just let me know.

**Comment by NoorhanAbbas** [comment]
Hello JJ,
I have added the paper and linked it to issue #6.  I won't add more papers until you have a look and let me know if what I did was right or not 🙂

Have a good day and thanks for your help,

Noorhan
________________________________
